cask_args appdir: "/Applications"


# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-fonts"

# System
brew "robotsandpencils/made/xcodes"
brew "cocoapods"
brew "fastlane"

# Terminal
brew "zsh"
brew "z"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "fzf"
cask "iterm2"

# Git
brew "git-lfs"
brew "gitui"
brew "lazygit"
cask "sourcetree"

# iOS/Swift
brew "swiftgen"
brew "swiftlint"
cask "pusher"

# Terminal Tools
brew "mas"
brew "httpie"
brew "curl"
brew "wget"
brew "bfg"
brew "vim"
brew "tree"
brew "cloc"
brew "ffmpeg"
brew "unzip"
brew "jq"
brew "aria2"
cask "ngrok"

# Fonts
cask "font-fira-code"

# UI Apps
cask "alfred"
cask "postman"
cask "slack"
cask "visual-studio-code"
cask "proxyman"
cask "macdown"


# Via Mac AppStore
mas "1Password 7", id: 1333542190
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Expressions", id: 913158085
mas "Grammarly for Safari", id: 1462114288
mas "Lockdown", id: 1483255076
mas "Moom", id: 419330170
#mas "Xcode", id: 497799835
